data_path: /links/groups/treutlein/DATA/imaging/charmel/publication_example_data_3/ #set path to the directory containing 'raw_data'.
proj_path: /home/pwahle/git_test/4i_publication_repo_2/ #set path to the directory containing this file.

cycles: 
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
            
to_collagen_mask: ['GLRA2','YAP1','NPC','RB1']

            
wells: [43,44] # corresponds to x.tif name wells 43 and 50. Script assumes that images are numbered continuous from 0 to x.
#ref_cycle: 2 #
ref_cycles: [2,7,12,17] # choose multiple if appropriate
cycles_bg: [0,6,12] #background cycles in which ABs were eluted but not restained.
